# Generated by Django 3.2.25 on 2025-07-04 16:52

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم (عربي)')),
                ('name_en', models.CharField(max_length=100, verbose_name='Name (English)')),
                ('logo', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('message_ar', models.TextField(verbose_name='الرسالة (عربي)')),
                ('message_en', models.TextField(verbose_name='Message (English)')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_ar', models.CharField(max_length=255, verbose_name='السؤال (عربي)')),
                ('question_en', models.CharField(max_length=255, verbose_name='Question (English)')),
                ('answer_ar', models.TextField(verbose_name='الجواب (عربي)')),
                ('answer_en', models.TextField(verbose_name='Answer (English)')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (English)')),
                ('category', models.CharField(choices=[('portrait', 'Portrait'), ('event', 'Event'), ('commercial', 'Commercial')], max_length=100)),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=100, verbose_name='العنوان (عربي)')),
                ('title_en', models.CharField(max_length=100, verbose_name='Title (English)')),
                ('description_ar', models.TextField(verbose_name='الوصف (عربي)')),
                ('description_en', models.TextField(verbose_name='Description (English)')),
                ('icon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SiteTextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value_ar', models.TextField(verbose_name='النص (عربي)')),
                ('value_en', models.TextField(verbose_name='Text (English)')),
                ('note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_ar', models.CharField(max_length=100, verbose_name='الدور (عربي)')),
                ('role_en', models.CharField(max_length=100, verbose_name='Role (English)')),
                ('image', models.ImageField(upload_to='team/')),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='المدينة أو الدولة')),
                ('content_ar', models.TextField(verbose_name='التعليق (عربي)')),
                ('content_en', models.TextField(verbose_name='Comment (English)')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم من 1 إلى 5')),
                ('facebook_url', models.URLField(blank=True, verbose_name='رابط فيسبوك')),
                ('twitter_url', models.URLField(blank=True, verbose_name='رابط تويتر')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='رابط لينكدإن')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
