# Generated by Django 3.2.25 on 2025-07-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0003_auto_20250705_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
