# Generated by Django 3.2.25 on 2025-07-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0004_auto_20250705_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_ar',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='message_en',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
