# Generated by Django 3.2.25 on 2025-07-06 12:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0005_auto_20250705_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('features', 'Features'), ('projects', 'Projects'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('clients', 'Clients'), ('video', 'Video')], max_length=50, verbose_name='Section')),
                ('type', models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('paragraph', 'Paragraph'), ('button', 'Button'), ('link', 'Link')], max_length=20, verbose_name='Content Type')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Unique Key')),
                ('content_ar', models.TextField(blank=True, verbose_name='Content (Arabic)')),
                ('content_en', models.TextField(blank=True, verbose_name='Content (English)')),
            ],
            options={
                'verbose_name': 'Static Content Item',
                'verbose_name_plural': 'Static Content',
                'ordering': ['key'],
                'unique_together': {('section', 'key')},
            },
        ),
        migrations.DeleteModel(
            name='SiteTextContent',
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='logo',
            field=models.ImageField(upload_to='public_site/clients/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='clientlogo',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='lastname',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sent At'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_ar',
            field=models.TextField(verbose_name='Answer (Arabic)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_ar',
            field=models.CharField(max_length=255, verbose_name='Question (Arabic)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='public_site/games/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='url',
            field=models.URLField(blank=True, verbose_name='Game URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(to='public_site.ProjectCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description_ar',
            field=models.TextField(blank=True, verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='public_site/projects/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title_ar',
            field=models.CharField(max_length=100, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name_ar',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ar',
            field=models.TextField(verbose_name='Description (Arabic)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=100, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_ar',
            field=models.CharField(max_length=100, verbose_name='Title (Arabic)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(upload_to='public_site/team/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_ar',
            field=models.CharField(max_length=100, verbose_name='Name (Arabic)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100, verbose_name='Name (English)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_ar',
            field=models.CharField(max_length=100, verbose_name='Role (Arabic)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='City or Country'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content_ar',
            field=models.TextField(verbose_name='Comment (Arabic)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating (1 to 5)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='Twitter URL'),
        ),
    ]
