# Generated by Django 3.2.25 on 2025-07-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0006_auto_20250706_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(choices=[('header', 'Header'), ('hero', 'Hero'), ('about', 'About'), ('games', 'Games'), ('features', 'Features'), ('projects', 'Projects'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('clients', 'Clients'), ('footer', 'Footer')], max_length=50, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('paragraph', 'Paragraph'), ('button', 'Button'), ('image', 'Image'), ('video', 'Video'), ('link', 'Link')], max_length=20, verbose_name='Content Type'),
        ),
    ]
