# Generated by Django 3.2.25 on 2025-07-06 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0008_auto_20250706_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='pages',
            field=models.CharField(default=1, help_text='Select pages separated by commas like: home,about', max_length=200, verbose_name='Pages (comma-separated)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(choices=[('header', 'Header'), ('hero', 'Hero'), ('about', 'About'), ('games', 'Games'), ('services', 'Services'), ('projects', 'Projects'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('clients', 'Clients'), ('footer', 'Footer')], max_length=50, verbose_name='Section'),
        ),
    ]
