# Generated by Django 3.2.25 on 2025-07-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0009_auto_20250706_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='pages',
            field=models.CharField(help_text='Select pages separated by commas like: home,about', max_length=200, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(choices=[('header', 'Header'), ('hero', 'Hero'), ('about', 'About'), ('games', 'Games'), ('services', 'Services'), ('projects', 'Projects'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('clients', 'Clients'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=50, verbose_name='Section'),
        ),
    ]
