# Generated by Django 3.2.25 on 2025-07-06 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0010_auto_20250707_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='pages',
        ),
    ]
