# Generated by Django 3.2.25 on 2025-07-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0011_remove_sitecontent_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('paragraph', 'Paragraph'), ('button', 'Button'), ('video', 'Video'), ('link', 'Link')], max_length=20, verbose_name='Content Type'),
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('header', 'Header'), ('home', 'home'), ('about', 'About'), ('projects', 'Projects'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=50, verbose_name='Section')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Unique Key')),
                ('image', models.ImageField(upload_to='public_site/site_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Site Lmage',
                'verbose_name_plural': 'Site Lmages',
                'ordering': ['key'],
                'unique_together': {('section', 'key')},
            },
        ),
    ]
