# Generated by Django 3.2.25 on 2025-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0012_auto_20250708_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (EN)')),
                ('title_ar', models.CharField(max_length=200, verbose_name='Title (AR)')),
                ('content_en', models.TextField(verbose_name='Content (EN)')),
                ('content_ar', models.TextField(verbose_name='Content (AR)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sitecontent',
            options={'ordering': ['key'], 'verbose_name': 'Site Content', 'verbose_name_plural': 'Site Content'},
        ),
        migrations.AlterModelOptions(
            name='siteimage',
            options={'ordering': ['key'], 'verbose_name': 'Site Image', 'verbose_name_plural': 'Site Images'},
        ),
    ]
