# Generated by Django 3.2.4 on 2025-07-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0013_auto_20250708_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='public_site/blog/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='section',
            field=models.CharField(choices=[('header', 'Header'), ('hero', 'Hero'), ('about', 'About'), ('games', 'Games'), ('services', 'Services'), ('projects', 'Projects'), ('faq', 'FAQ'), ('testimonials', 'Testimonials'), ('team', 'Team'), ('blog', 'Blog'), ('clients', 'Clients'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=50, verbose_name='Section'),
        ),
        migrations.AlterField(
            model_name='siteimage',
            name='section',
            field=models.CharField(choices=[('header', 'Header'), ('home', 'home'), ('about', 'About'), ('projects', 'Projects'), ('blog', 'Blog'), ('contact', 'Contact'), ('footer', 'Footer')], max_length=50, verbose_name='Section'),
        ),
    ]
