# Generated by Django 3.2.4 on 2025-07-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0014_auto_20250712_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
